apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartretailx-gateway
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:REGION:ACCOUNT_ID:certificate/PROD_CERTIFICATE_ID
    alb.ingress.kubernetes.io/tags: Environment=prod,Project=smartretailx
    # WAF association (optional) — replace with your Web ACL ARN
    # alb.ingress.kubernetes.io/wafv2-acl-arn: arn:aws:wafv2:REGION:ACCOUNT_ID:regional/webacl/NAME/ID
spec:
  rules:
    - host: api.smartretailx.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80
