apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  labels:
    app: user-service
    app.kubernetes.io/name: user-service
    app.kubernetes.io/part-of: smartretailx
data:
  PORT: "3001"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  SERVICE_NAME: "user-service"
  JWT_EXPIRES_IN: "24h"
