apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: user-service
  labels:
    app: user-service
    app.kubernetes.io/name: user-service
    app.kubernetes.io/part-of: smartretailx
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: user-service
