
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  labels:
    app: user-service
    app.kubernetes.io/name: user-service
    app.kubernetes.io/part-of: smartretailx
type: Opaque
stringData:
  JWT_SECRET: "fb843c5ae7567abca3d4b63735e535fa48f30c90a6a415d66b276c325701560c"
