apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  labels:
    app: order-service
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: smartretailx
data:
  PORT: "3003"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  SERVICE_NAME: "order-service"
  CATALOGUE_SERVICE_URL: "http://catalogue-service:3002"
  PAYMENT_SERVICE_URL: "http://payment-service:3004"
  EVENT_BUS_ENABLED: "true"
