apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-service
  labels:
    app: order-service
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: smartretailx
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: order-service
