
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
  labels:
    app: order-service
    app.kubernetes.io/name: order-service
    app.kubernetes.io/part-of: smartretailx
type: Opaque
stringData:
  PAYMENT_API_KEY: "660564602415a5561a7403558564f3cf6a9e0c9a66e52c6c46eab8941a8d59a7"
