apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-service-config
  labels:
    app: catalogue-service
    app.kubernetes.io/name: catalogue-service
    app.kubernetes.io/part-of: smartretailx
data:
  PORT: "3002"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  SERVICE_NAME: "catalogue-service"
