apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  labels:
    app: gateway
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: smartretailx
data:
  PORT: "3000"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  SERVICE_NAME: "gateway"
  AWS_XRAY_ENABLED: "true"
  AWS_XRAY_DAEMON_ADDRESS: "127.0.0.1:2000"
  USER_SERVICE_URL: "http://user-service:3001"
  CATALOGUE_SERVICE_URL: "http://catalogue-service:3002"
  ORDER_SERVICE_URL: "http://order-service:3003"
  PAYMENT_SERVICE_URL: "http://payment-service:3004"
  INVENTORY_SERVICE_URL: "http://inventory-service:3005"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3006"
