apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway
  labels:
    app: gateway
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: smartretailx
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: gateway
