apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  labels:
    app: gateway
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: smartretailx
type: Opaque
stringData:
  GATEWAY_API_KEY: "cb25bb99663f3d23ac8267b507e3fd52fbd63f40d87b42e1b641403bf73fbabc"
