apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartretailx-gateway
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:REGION:ACCOUNT_ID:certificate/DEV_CERTIFICATE_ID
    alb.ingress.kubernetes.io/tags: Environment=dev,Project=smartretailx
spec:
  rules:
    - host: api.dev.smartretailx.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80
