apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smartretailx

resources:
  - namespace.yaml
  - user-service
  - catalogue-service
  - order-service
  - gateway
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: smartretailx
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
