apiVersion: v1
kind: Namespace
metadata:
  name: smartretailx
  labels:
    app.kubernetes.io/part-of: smartretailx
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
